[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@thirdweb-dev/contracts=lib/contracts/contracts"]
evm_version = "london"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
